version: '3.5'

services:
  elasnacamera:
    build: ./
    container_name: elasnacamera
    volumes:
      - ./:/usr/src/app/
    networks:
      - elasnacamera_network
    logging:
      driver: "json-file"
      options:
        max-file: '100'
        max-size: 1m
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - elasnacamera_network
    restart: unless-stopped

networks:
    elasnacamera_network:
      driver: bridge
      name: elasnacamera_network
